name: attendance
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.0.3
  lottie: 1.3.0
  google_maps_flutter: ^2.1.10
  slide_to_act: ^2.0.1
  syncfusion_flutter_charts: ^20.2.43
  camera: ^0.10.0+4
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  location: ^4.4.0
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  # firebase_core: ^2.3.0
  # firebase_auth: ^4.1.5
  device_info_plus: ^8.0.0
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.9.3
  modal_bottom_sheet: ^2.1.2




  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/lotties/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
  uses-material-design: true
